myshop/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',
        views.cart_detail,
        name='cart_detail'),

    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),

    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),

]

myshop/coupons/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^apply/$',
        views.coupon_apply,
        name='apply')
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(_(r'^cart/'), include('cart.urls', namespace='cart')),
    url(_(r'^orders/'), include('orders.urls', namespace='orders')),
    url(_(r'^coupons/'), include('coupons.urls', namespace='coupons')),
    url(r'^rosetta', include('rosetta.urls')),
    url(r'^', include('shop.urls', namespace='shop'))
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^create/$',
        views.order_create,
        name='order_create'),

    url(r'^admin/order/(?P<order_id>\d+)/$',
        views.admin_order_detail,
        name='admin_order_detail'),
]

myshop/shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.product_list,
        name='product_list'),

    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),

    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int,
                                label=_('Quantity'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from shop.recommender import Recommender
from coupons.forms import CouponsApplyForm
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    context = {}
    if len(cart):
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                                    initial={'quantity': item['quantity'],
                                             'update': True})
        coupon_apply_form = CouponsApplyForm()

        r = Recommender()
        cart_products = [item['product'] for item in cart]
        recommended_products = r.suggest_product_for(cart_products)
        context = {'cart': cart,
                   'coupon_apply_form': coupon_apply_form,
                   'recommended_products': recommended_products}

    return render(request,
                  'cart/detail.html',
                  context)

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %} Your shopping cart {% endblock %}

{% block content %}
    {% if cart %}
        <h1>Your shopping cart</h1>
        <table class="cart table table-striped table-hover">
            <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
            </thead>

            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="
                                        {% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                {% csrf_token %}
                                <input class="btn btn-default btn-sm" type="submit" value="Update">
                            </form>
                        </td>
                        <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">${{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}

            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <td class="num">${{ cart.get_total_price }}</td>
                </tr>
                <tr>
                    <td>"{{ cart.coupon.code }}" coupon ({{ cart.coupon.discount }}% off)</td>
                    <td colspan="4"></td>
                    <td class="num neg">- ${{ cart.get_discount|floatformat:"2" }}</td>
                </tr>
            {% endif %}
            <tr class="total info">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price_after_discount|floatformat:"2" }}</td>
            </tr>
            </tbody>
        </table>

        <p>Apply a coupon:</p>
        <form action="{% url "coupons:apply" %}" method="post">
            {{ coupon_apply_form }}
            <input type="submit" value="Apply">
            {% csrf_token %}
        </form>

        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="button light btn btn-default ">Continue shopping</a>
            <a href="{% url "orders:order_create" %}" class="button btn btn-success">Checkout</a>
        </p>

        {% if recommended_products %}
            <div class="recommendations">
                <h3>People who bought this also bought</h3>

                {% for p in recommended_products %}
                    <div class="item">
                        <a href="{{ p.get_absolute_url }}">
                            <img src="
                                    {% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                        </a>
                        <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
                    </div>
                {% endfor %}

            </div>
        {% endif %}

    {% else %}
        <h1>Your shopping cart is empty</h1>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="button light btn btn-default ">Continue shopping</a>
        </p>
    {% endif %}

{% endblock %}